//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.18052
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using UnityEngine;

public class PathNode
{
	GameObject gameObject;
	public string name;
	List<PathEdge> edgesTo;
	
	public PathNode (string name)
	{
		gameObject = null;
		this.name = name;
		edgesTo = new List<PathEdge>();
	}
	
	public PathNode (string name, GameObject gameObject)
	{
		this.gameObject = gameObject;
		this.name = name;
		edgesTo = new List<PathEdge>();
	}
	
	public void addEdge(PathNode node)
	{
		edgesTo.Add(new PathEdge(this, node));
	}

	public List<PathEdge> getEdges()
	{
		return edgesTo;
	}
}