//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.18052
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;

public class Path
{
	Queue<PathEdge> path;

	public Path ()
	{
		path = new Queue<PathEdge>();
	}

	public void addEdge(PathEdge edge)
	{
		path.Enqueue(edge);
	}

	public PathEdge getNextEdge()
	{
		return path.Dequeue();
	}

	public bool isEmpty()
	{
		return (path.Count == 0);
	}

	public String getString()
	{
		string p = "";
		while(!isEmpty())
		{
			p += getNextEdge().getNodeTo().name + " ";
		}
		return p;
	}
}