//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.18052
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;
public class WaveManager : MonoBehaviour
{
	public GameObject enemyPrefab;
	public Board board;
	public Map map;
	int level;
	int numberOfEnemies;
	bool waveStarted;
	
	public WaveManager ()
	{
		level = 0;
		numberOfEnemies = 0;
		waveStarted = false;
	}

	public void startNextWave()
	{
		level++;
		numberOfEnemies = level*2;
		waveStarted = true;
	}

	/*public Path getEnemyPath()
	{

	}*/
}

