//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.18052
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Collections;
using UnityEngine;
public class WaveManager : MonoBehaviour
{
	public GameObject enemyPrefab;
	public Map map;
	int level;
	int numberOfEnemies;
	bool waveStarted;
	bool invoked;
	
	void Start()
	{
		map = Map.Instance;
		level = 0;
		numberOfEnemies = -1;
		waveStarted = false;
		invoked = false;
	}

	void FixedUpdate()
	{
		GameObject[] ennemies = GameObject.FindGameObjectsWithTag("Enemy");

		Debug.Log (ennemies.Length);

		if (ennemies.Length == 0 && waveStarted) {
			waveStarted = false;
			invoked = false;
		}
		if (numberOfEnemies > 0 && !invoked) {
			Invoke ("addEnnemies", 3);
			invoked = true;
		} else if (!waveStarted) {
			waveStarted = true;
			StartCoroutine(startNextWave());
		}
	}
	public IEnumerator startNextWave()
	{
		yield return new WaitForSeconds (2);
		level++;	
		numberOfEnemies = level*2;
	}

	public Path getEnemyPath(string startNode)
	{
		Path path = map.createPath(map.getNodeByName(startNode), map.getNodeByName("F1"));
		return path;
	}

	public void addEnnemies()
	{
		string[] startNode = new string[] {"A1", "A2", "A3"};
		for(int i=0;i<3;i++)
		{
			if(numberOfEnemies > 0)
			{
				Path enemyPath = getEnemyPath(startNode[i]);
				enemyPrefab.transform.position = map.getNodeByName(startNode[i]).gameObject.transform.position;
				GameObject enemyObject = (GameObject)Instantiate(enemyPrefab);
				EnemyScript enemy = enemyObject.GetComponent<EnemyScript>();
				enemy.setPath(enemyPath);
				numberOfEnemies--;
			}
		}
	}
}

